apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev4
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      name: rev4
  template:
    metadata:
      labels:
        name: rev4
    spec:
      containers:
      - name: rev4
        image: okliukin/rev4:1.0
        ports:
         - containerPort: 8080
        env:
        - name: PGHOST
          value: rev4-pg
        - name: PGDATABASE
          value: rev4
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: rev4.rev4-pg.credentials
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: rev4.rev4-pg.credentials
              key: password
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rev4-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: rev4
  type: LoadBalancer
