apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-infrastructure-roles
data:
  rev4: |
    user_flags:
      - createdb
    db_parameters:  # db parameters, applyed for this particular user
      log_statement: all
